# syntax=docker/dockerfile:1
FROM python:3.10-slim-buster
WORKDIR /srv/data/ais/backend

RUN apt-get update
RUN apt-get install -y python3.9-dev
RUN add-apt-repository ppa:ubuntugis/ppa &&  apt-get update

RUN apt install -y gdal-bin libgdal-dev

RUN python -m venv /opt/venv
# Enable venv
ENV PATH="/opt/venv/bin:$PATH"

ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal

COPY backend/requirements.txt requirements.txt
RUN pip3 install -r requirements.txt