version: '3.3'
services:
  db:
    image: postgis/postgis
    container_name: postgres_db
    ports:
      - '5431:5431'
    env_file: ../.env
    restart: always
    environment:
      - TZ=Europe/Copenhagen
    
  api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.API
    image: ais_api
    container_name: ais_api
    volumes:
      - type: bind
        source: ../
        target: /srv/data/ais
      - type: bind
        source: 'C:\\Users\\Krist\\Desktop\\data_ais\\'
        target: /srv/data/csv/
    restart: always
    ports:
      - 8080:8000
    environment:
      - TZ=Europe/Copenhagen
    command: uvicorn app.main:app --host 0.0.0.0 --reload
      
  client:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.Client
    image: ais_client
    container_name: ais_client
    volumes:
      - type: bind
        source: ../
        target: /srv/data/ais
    restart: always
    ports:
      - 3000:3000
    environment:
      - TZ=Europe/Copenhagen
    command: npm start
    
  cleansing:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.Cleansing
    tty: true
    image: ais_cleansing
    container_name: ais_cleansing
    command: python main.py -f True
    volumes:
      - type: bind
        source: ../
        target: /srv/data/ais
      - type: bind
        source: ../csv
        target: /srv/data/csv
    restart: always
    environment:
      - TZ=Europe/Copenhagen