# syntax=docker/dockerfile:1
FROM python:latest
WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY ../. .



#For if we want to run the app right away
#CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]