version: '2'
services:
  postgres:
    image: postgis/postgis
    container_name: postgres_db
    volumes:
      - /srv/data/db/postgresql/data:/var/lib/postgresql/data
      - /srv/data/db/csv
    networks:
      - postgres_conn
    ports:
      - '5432:5432'
    env_file: ../.env
  python:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.pythonProject
    image: ais_project
    container_name: ais_project
    volumes:
      - type: bind
        source: ../
        target: /srv/data/ais

    ports:
      - "8000:5000"

networks:
  postgres_conn:
    driver: bridge