version: '3.3'
services:
  db:
    image: postgis/postgis
    container_name: postgres_db
    cpu_count: 16
    cpu_percent: 100
    volumes:
      - type: bind
        source: /srv/data/db/postgresql/data
        target: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file: ../.env
    restart: always
    
  api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.API
    image: ais_api
    container_name: ais_api
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - type: bind
        source: ../
        target: /srv/data/ais
      - type: bind
        source: /srv/data/csv
        target: /srv/data/csv
    restart: always
    ports:
      - 8080:8000
    
  client:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.Client
    image: ais_client
    container_name: ais_client
    command: npm start
    volumes:
      - type: bind
        source: ../
        target: /srv/data/ais
    restart: always
    ports:
      - 3000:3000

  cleansing:
    cpu_count: 16
    cpu_percent: 100
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.Cleansing
    tty: true
    image: ais_cleansing
    container_name: ais_cleansing
    volumes:
      - type: bind
        source: ../
        target: /srv/data/ais
      - type: bind
        source: /srv/data/csv
        target: /srv/data/csv
    restart: always