FROM postgis/postgis

# add backup job
RUN mkdir -p /srv/data/db/postgresql/backups/backups
COPY /db_setup/db_backup.sh /srv/data/db/postgresql/backups/db_backup.sh
RUN chmod +x /srv/data/db/postgresql/backups/db_backup.sh

# Init script, for when we have some data
RUN mkdir -p /srv/data/db/postgresql/docker-entrypoint-initdb.d
COPY /db_setup/initdb-postgis.sh /srv/data/db/postgresql/docker-entrypoint-initdb.d/postgis.sh

# create volume for backups
VOLUME ["/srv/data/db/postgresql/backups"]