version: '3.3'
services:
  postgres:
    image: postgis/postgis
    container_name: postgres_db
    volumes:
      - type: bind
      - source: /srv/data/db/postgresql/data
      - target: /var/lib/postgresql/data
      - type: bind
      - source: /srv/data/db/csv
      - target: /srv/data/db/csv
    networks:
      - postgres_conn
    ports:
      - '5432:5432'
    env_file: ../.env
    restart: always
  python:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.aisProject
    image: ais_project
    container_name: ais_project
    volumes:
      - type: bind
        source: ../
        target: /srv/data/ais
    restart: always
    ports:
      - "8000:5000"
    networks:
      - postgres_conn
    
networks:
  postgres_conn:
    driver: bridge