version: '3.3'
services:
  db:
    image: postgis/postgis
    container_name: postgres_db
    ports:
      - '5431:5431'
    env_file: ../.env
    restart: always
  project:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.aisProject
    image: ais_project
    container_name: ais_project
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - type: bind
        source: ../
        target: /srv/data/ais
    restart: always
    ports:
      - 8008:8000