version: '2'
services:
  postgres:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.postgresDB
    image: postgres_db
    container_name: postgres_db
    volumes:
      - /srv/data/db/postgresql/data:/var/lib/postgresql/data
      - /srv/data/db/postgresql/backups
      - /srv/data/db/csv
    networks:
      - postgres_conn
    ports:
      - '5432:5432'
    env_file: ../.env
  python:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.pythonProject
    image: python_project
    container_name: python_project
    ports:
      - "8000:5000"


networks:
  postgres_conn:
    driver: bridge