# syntax=docker/dockerfile:1
FROM python:latest

WORKDIR /srv/data/ais/backend/app/ais_data_handling

RUN apt-get update

RUN apt install -y gdal-bin libgdal-dev

RUN python -m venv /opt/venv
# Enable venv
ENV PATH="/opt/venv/bin:$PATH"

ENV CPLUS_INCLUDE_PATH=/usr/include/gddal
ENV C_INCLUDE_PATH=/usr/include/gdal

COPY ./backend/requirements.txt requirements.txt
RUN pip3 install -r requirements.txt