# syntax=docker/dockerfile:1
FROM python:latest
WORKDIR /srv/data/ais/backend

# Install GDAL dependencies
RUN apt-get install -y gdal-bin libgdal-dev

# Update C env vars so compiler can find gdal
ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal

RUN python -m venv /opt/venv
# Enable venv
ENV PATH="/opt/venv/bin:$PATH"

COPY backend/requirements.txt requirements.txt
RUN pip3 install -r requirements.txt